/**
 * Long-horizon simulator for the player-paced Career package.
 *
 * This module is analysis-only: it has no database, clock, route, or UI
 * dependencies. It uses the frozen v2 formula bundle, the production ranking
 * and movement primitives, and score banks generated by the real hole engine.
 */
import { hashSeed } from "@/lib/engine/rng";

import {
  assignCareerBotSlots,
  generateCareerBotRoster,
  type CareerBotIdentity,
} from "./botRoster";
import { championshipUnlock } from "./championship";
import {
  rankChampionshipField,
  type ChampionshipSettlementCompetitor,
} from "./championshipSettlement";
import { CAREER_V3_FORMULA_BUNDLE } from "./formulaBundle";
import {
  blankLegacyAwardCounts,
  legacyPoints,
  promoteTier,
  rankEvent,
  rankSeason,
  relegateTier,
  seasonRating,
  tourRating,
  type CareerTier,
  type LegacyAwardCounts,
  type MovementAction,
  type RatingSeason,
  type SeasonCompetitor,
  type SeasonEventResult,
} from "./rules";
import {
  activeSeasonPercentile,
  rollingHistoryAfterPromotion,
  rollingMovementForSeason,
  type AbilityBand,
  type CareerArchetype,
  type ScoreBank,
  type Tendency,
} from "./simulator";

const FORMULA = CAREER_V3_FORMULA_BUNDLE;
const FIELD_SIZE = FORMULA.championship.fieldSize;
const EVENTS_PER_SEASON = FORMULA.eventPoints.scheduledEvents;

export interface PlayerPacedCareerConfig {
  readonly seed: string;
  readonly seasons: number;
  readonly ability: AbilityBand;
  readonly tendency?: Tendency;
  readonly scoreBank: ScoreBank;
  /** The product allows Championships to remain unplayed. Long-horizon Legacy
   * calibration defaults to a player who contests every unlocked Championship. */
  readonly playChampionships?: boolean;
}

export interface PlayerPacedSeasonRecord {
  readonly season: number;
  readonly tier: CareerTier;
  readonly nextTier: CareerTier;
  readonly rank: number;
  readonly percentile: number;
  readonly movement: MovementAction;
  readonly seasonRating: number;
  readonly tourRating: number;
  readonly legacyEarned: number;
  readonly legacyTotal: number;
  readonly championshipQualified: boolean;
  readonly championshipWon: boolean;
}

export interface PlayerPacedCareerSimulation {
  readonly seed: string;
  readonly formulaVersion: string;
  readonly ability: AbilityBand;
  readonly tendency: Tendency;
  readonly histories: readonly PlayerPacedSeasonRecord[];
  readonly firstProSeason: number | null;
  readonly firstChampionshipSeason: number | null;
  readonly relegations: number;
  readonly proSeasons: number;
  readonly proSeasonsSurvived: number;
}

interface CompetitorArchetype {
  readonly competitorId: string;
  readonly archetype: CareerArchetype;
}

function sampleScore(
  bank: ScoreBank,
  archetype: CareerArchetype,
  namespace: string,
): number {
  const scores = bank.scores.get(`${archetype.ability}:${archetype.tendency}`);
  if (!scores?.length) {
    throw new Error(
      `Player-paced simulator score bank is missing ${archetype.ability}:${archetype.tendency}`,
    );
  }
  return scores[hashSeed(`${bank.seed}:${namespace}`) % scores.length];
}

function fallbackDraw(namespace: string): number {
  return hashSeed(namespace);
}

function dbTier(tier: CareerTier): "LOCAL" | "CHALLENGER" | "PRO" {
  return tier.toUpperCase() as "LOCAL" | "CHALLENGER" | "PRO";
}

function seasonField(
  seed: string,
  season: number,
  tier: CareerTier,
  human: CareerArchetype,
  roster: readonly CareerBotIdentity[],
): readonly CompetitorArchetype[] {
  const worldKey = `simulation:${seed}`;
  const assignments = assignCareerBotSlots({
    worldKey,
    seasonNumber: season,
    tier,
    eventNumber: 1,
    slots: Array.from({ length: FIELD_SIZE - 1 }, (_, index) => ({
      slotId: index + 2,
      slotIndex: index,
    })),
    roster,
  });
  return [
    { competitorId: "human:player", archetype: human },
    ...assignments.map((assignment) => ({
      competitorId: `bot:${assignment.identity.botKey}`,
      archetype: {
        ability: assignment.abilityBand,
        tendency: assignment.tendency,
      },
    })),
  ];
}

function simulateSeasonEvents(
  seed: string,
  season: number,
  tier: CareerTier,
  field: readonly CompetitorArchetype[],
  bank: ScoreBank,
): Map<string, SeasonEventResult[]> {
  const eventsByCompetitor = new Map<string, SeasonEventResult[]>(
    field.map((competitor) => [competitor.competitorId, []]),
  );
  for (let eventIndex = 0; eventIndex < EVENTS_PER_SEASON; eventIndex++) {
    const standings = rankEvent(field.map((competitor) => ({
      competitorId: competitor.competitorId,
      relativeToPar: Array.from({ length: 4 }, (_, roundIndex) =>
        sampleScore(
          bank,
          competitor.archetype,
          `${seed}:season:${season}:${tier}:event:${eventIndex}`
          + `:round:${roundIndex}:${competitor.competitorId}`,
        )).reduce((sum, score) => sum + score, 0),
    })));
    for (const standing of standings) {
      eventsByCompetitor.get(standing.competitorId)!.push({
        ...standing,
        eventIndex,
      });
    }
  }
  return eventsByCompetitor;
}

function regularSeasonLegacy(
  humanEvents: readonly SeasonEventResult[],
  movement: MovementAction,
  tier: CareerTier,
  isSeasonChampion: boolean,
  championshipQualified: boolean,
): LegacyAwardCounts {
  const awards = blankLegacyAwardCounts();
  awards.eventCompletion = humanEvents.filter((event) => event.completed).length;
  awards.eventTopFive = humanEvents.filter(
    (event) => event.completed && event.rank != null && event.rank <= 5,
  ).length;
  awards.eventWin = humanEvents.filter(
    (event) => event.completed && event.rank === 1,
  ).length;
  awards.activeSeasonCompletion = 1;
  if (movement === "promote") awards.promotion = 1;
  if (tier === "pro" && movement !== "relegate") awards.proSurvival = 1;
  if (isSeasonChampion) awards.seasonChampionship = 1;
  if (championshipQualified) awards.championshipQualification = 1;
  return awards;
}

function simulateChampionshipWin(
  seed: string,
  cycleNumber: number,
  human: CareerArchetype,
  roster: readonly CareerBotIdentity[],
  bank: ScoreBank,
): boolean {
  const competitors: ChampionshipSettlementCompetitor[] = [
    {
      slotNumber: 1,
      competitorId: "human:player",
      competitorType: "HUMAN",
      profileId: "player",
      botIdentityId: null,
      relativeToPar: sampleScore(
        bank,
        human,
        `${seed}:championship:${cycleNumber}:human`,
      ),
      fallbackDraw: fallbackDraw(`${seed}:championship:${cycleNumber}:human:fallback`),
    },
    ...roster.slice(0, FIELD_SIZE - 1).map((identity, index) => ({
      slotNumber: index + 2,
      competitorId: `bot:${identity.botKey}`,
      competitorType: "BOT" as const,
      profileId: null,
      botIdentityId: identity.botKey,
      relativeToPar: sampleScore(
        bank,
        { ability: "ace", tendency: identity.tendency },
        `${seed}:championship:${cycleNumber}:bot:${identity.botKey}`,
      ),
      fallbackDraw: fallbackDraw(
        `${seed}:championship:${cycleNumber}:bot:${identity.botKey}:fallback`,
      ),
    })),
  ];
  return rankChampionshipField(
    `simulation:${seed}:championship:${cycleNumber}`,
    competitors,
  ).winnerCompetitorId === "human:player";
}

export function simulatePlayerPacedCareer(
  config: PlayerPacedCareerConfig,
): PlayerPacedCareerSimulation {
  if (!Number.isSafeInteger(config.seasons) || config.seasons < 1) {
    throw new TypeError("Player-paced simulation seasons must be a positive safe integer");
  }
  if (
    config.scoreBank.model !== FORMULA.ability.model
    || JSON.stringify(config.scoreBank.errorRates) !== JSON.stringify(FORMULA.ability.errorRates)
  ) {
    throw new Error(
      `Player-paced simulation requires a ${FORMULA.id} real-engine score bank`,
    );
  }

  const tendency = config.tendency ?? "balanced";
  const human = { ability: config.ability, tendency } as const;
  const roster = generateCareerBotRoster(`simulation:${config.seed}`);
  const histories: PlayerPacedSeasonRecord[] = [];
  const ratingHistory: RatingSeason[] = [];
  let tier: CareerTier = "local";
  let movementEvidence: number[] = [];
  let legacyTotal = 0;
  let firstProSeason: number | null = null;
  let firstChampionshipSeason: number | null = null;
  let relegations = 0;
  let proSeasons = 0;
  let proSeasonsSurvived = 0;

  for (let season = 1; season <= config.seasons; season++) {
    const field = seasonField(config.seed, season, tier, human, roster);
    const eventsByCompetitor = simulateSeasonEvents(
      config.seed,
      season,
      tier,
      field,
      config.scoreBank,
    );
    const standings = rankSeason(field.map((competitor): SeasonCompetitor => ({
      competitorId: competitor.competitorId,
      events: eventsByCompetitor.get(competitor.competitorId)!,
      fallbackDraw: fallbackDraw(
        `${config.seed}:season:${season}:${tier}:${competitor.competitorId}:fallback`,
      ),
    })));
    const humanRank = standings.findIndex(
      (standing) => standing.competitorId === "human:player",
    ) + 1;
    const percentile = activeSeasonPercentile(standings.length, humanRank);
    const rolling = rollingMovementForSeason(
      movementEvidence,
      percentile,
      tier,
      {
        window: FORMULA.movement.rollingWindow,
        minEntries: FORMULA.movement.rollingMinEntries,
        promoteThreshold: FORMULA.movement.rollingPromoteThreshold,
        promotionFloor: FORMULA.movement.rollingPromotionFloor,
        relegateThreshold: FORMULA.movement.rollingRelegateThreshold,
      },
    );
    const movement = rolling.action;
    let nextTier: CareerTier = tier;
    if (movement === "promote") nextTier = promoteTier(tier);
    if (movement === "relegate") nextTier = relegateTier(tier);
    movementEvidence = rolling.history;
    if (nextTier !== tier) {
      movementEvidence = movement === "promote"
        ? rollingHistoryAfterPromotion(
          movementEvidence,
          FORMULA.movement.rollingPromotionCarryWeight,
        )
        : [];
    }

    const rating = seasonRating(
      standings.length,
      humanRank,
      tier,
      FORMULA.tourRating.tierMultipliers,
    );
    ratingHistory.push({ rating, active: true });
    const currentTourRating = tourRating(ratingHistory);
    const unlock = championshipUnlock(season, dbTier(nextTier));
    const championshipQualified = unlock.unlocked;
    const championshipWon = Boolean(
      championshipQualified
      && (config.playChampionships ?? true)
      && simulateChampionshipWin(
        config.seed,
        unlock.cycleNumber!,
        human,
        roster,
        config.scoreBank,
      ),
    );
    const humanEvents = eventsByCompetitor.get("human:player")!;
    const awards = regularSeasonLegacy(
      humanEvents,
      movement,
      tier,
      standings[0]?.competitorId === "human:player",
      championshipQualified,
    );
    if (championshipWon) awards.championshipWin = 1;
    const legacyEarned = legacyPoints(awards, FORMULA.legacyPoints);
    legacyTotal += legacyEarned;

    if (movement === "relegate") relegations++;
    if (tier === "pro") {
      proSeasons++;
      if (nextTier === "pro") proSeasonsSurvived++;
    }
    if (firstProSeason == null && nextTier === "pro") firstProSeason = season + 1;
    if (firstChampionshipSeason == null && championshipQualified) {
      firstChampionshipSeason = season;
    }
    histories.push({
      season,
      tier,
      nextTier,
      rank: humanRank,
      percentile,
      movement,
      seasonRating: rating,
      tourRating: currentTourRating,
      legacyEarned,
      legacyTotal,
      championshipQualified,
      championshipWon,
    });
    tier = nextTier;
  }

  return {
    seed: config.seed,
    formulaVersion: FORMULA.id,
    ability: config.ability,
    tendency,
    histories,
    firstProSeason,
    firstChampionshipSeason,
    relegations,
    proSeasons,
    proSeasonsSurvived,
  };
}
